# Generated by Django 4.2.9 on 2024-01-25 13:30

from django.db import migrations
import json
from django.contrib.gis.geos import Point
from pathlib import Path

DATA_FILENAME = 'export.geojson'

def load_geojson_data(apps, schema_editor):
    Shop = apps.get_model('najbliziducani', 'Shop')
    jsonfile = Path(__file__).resolve().parent.parent / DATA_FILENAME

    with open(str(jsonfile), encoding='utf-8') as datafile:
        data = json.load(datafile)
        for feature in data['features']:
            properties = feature['properties']
            geometry = feature['geometry']

            ime = properties.get('name', '')
            longitude, latitude = geometry['coordinates']
            lokacija = Point(longitude, latitude, srid=4326)
            adresa = f"{properties.get('addr:housenumber', '')} {properties.get('addr:street', '')}"
            grad = properties.get('addr:city', '')
            radno_vrijeme = properties.get('opening_hours', '')
            web = properties.get('website', '')

            Shop(ime=ime, lokacija=lokacija, adresa=adresa, grad=grad, radno_vrijeme=radno_vrijeme, web=web).save()


class Migration(migrations.Migration):

    dependencies = [
        ('najbliziducani', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_geojson_data)
    ]
